In [3]:
import pandas as pd
import numpy as np

In [2]:
obj = pd.Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [10]:
obj2['d'] = 6

In [11]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [12]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [13]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [14]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [15]:
'b' in obj2

True

In [16]:
'e' in obj2

False

In [17]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [18]:
obj3 = pd.Series(sdata)

In [19]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [20]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [21]:
obj4 = pd.Series(sdata, index = states)

In [22]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [23]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [25]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [29]:
obj4.name= 'population'

In [30]:
obj4.index.name = 'state'

In [31]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [32]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [33]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [34]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

#### 5.1.2 DataFrame

In [35]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year' : [2000, 2001, 2002, 2001, 2002, 2003],
    'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

In [36]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [37]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [38]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [39]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])

In [40]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [41]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [42]:
import IPython
print(IPython.sys_info())

{'commit_hash': '8bda98619',
 'commit_source': 'installation',
 'default_encoding': 'utf-8',
 'ipython_path': '/opt/anaconda3/envs/product_text_analysis/lib/python3.8/site-packages/IPython',
 'ipython_version': '7.12.0',
 'os_name': 'posix',
 'platform': 'macOS-10.15.7-x86_64-i386-64bit',
 'sys_executable': '/opt/anaconda3/envs/product_text_analysis/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.8.5 (default, Sep  4 2020, 02:22:02) \n[Clang 10.0.0 ]'}


In [43]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [44]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [45]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [46]:
frame2['debt'] = 16.5

In [47]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [48]:
frame2['debt'] = np.arange(6)

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [50]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [51]:
frame2['debt'] = val

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [53]:
frame2['eastern'] = frame2.state == 'Ohio'

In [54]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [55]:
del frame2['eastern']

In [56]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [57]:
pop = {
    'Nevada': {2001:2.4, 2002:2.9},
    'Ohio': {2000:1.5, 2001:1.7, 2002:3.6}}

In [58]:
frame3 = pd.DataFrame(pop)

In [59]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [60]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [61]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [62]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [63]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [64]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [65]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [66]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [67]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 5.1.3 색인 객체

In [68]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [69]:
index = obj.index

In [70]:
index

Index(['a', 'b', 'c'], dtype='object')

In [71]:
index[1:]

Index(['b', 'c'], dtype='object')

In [72]:
#index[1] = 'b'

In [73]:
labels = pd.Index(np.arange(3), dtype=np.int32)

In [74]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [75]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [76]:
obj2.index is labels

True

In [77]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [78]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [79]:
'Ohio' in frame3.columns

True

In [80]:
2003 in frame3.index

False

In [81]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [82]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 핵심 기능

### 5.2.1 재색인

In [83]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [84]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [85]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [86]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [87]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [88]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [89]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [90]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'] )

In [91]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [92]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [93]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [94]:
states = ['Texas', 'Utah', 'California']

In [95]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [96]:
frame.loc[['a','c', 'd'], ['Ohio', 'Texas', 'California']]

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

### 5.2.2 하나의 로우나 컬럼 삭제하기

In [97]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [98]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [99]:
new_obj = obj.drop('c')

In [100]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [101]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [102]:
data = pd.DataFrame(np.arange(16).reshape(-1, 4), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [103]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [104]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [105]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [106]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [107]:
obj.drop('c', inplace=True)

In [108]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 5.2.3 색인하기, 선택하기, 거르기

In [109]:
ojb = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [110]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [111]:
obj['b']

1.0

In [112]:
obj[1]

1.0

In [113]:
obj[2:4]

d    3.0
e    4.0
dtype: float64

In [114]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [115]:
obj[[1,3]]

b    1.0
e    4.0
dtype: float64

In [116]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [117]:
obj['b':'c']

b    1.0
dtype: float64

In [118]:
obj['b':'c'] = 5

In [119]:
obj

a    0.0
b    5.0
d    3.0
e    4.0
dtype: float64

In [4]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [121]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [123]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [124]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [125]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [126]:
data[data<5] = 0

In [127]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### loc과 iloc으로 선택하기

In [6]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [129]:
data.iloc[2, [3, 0 ,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [130]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [131]:
data.iloc[[1,2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [132]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [133]:
data.iloc[:, :3][data.three > 3]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### 5.2.4 정수 색인

In [134]:
ser = pd.Series(np.arange(3.))

In [135]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [136]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [137]:
ser2[-1]

2.0

In [138]:
ser[:1]

0    0.0
dtype: float64

In [139]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [140]:
ser.iloc[:1]

0    0.0
dtype: float64

### 5.2.5 산술 연산과 데이터 정렬

In [141]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [142]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [143]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [144]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [145]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [146]:
df1 = pd.DataFrame(np.arange(9.).reshape(3 ,3), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [147]:
df2 = pd.DataFrame(np.arange(12.).reshape(4 ,3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [148]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [149]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [150]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [151]:
df1 = pd.DataFrame({'A':[1, 2]})

In [152]:
df2 = pd.DataFrame({'B':[3, 4]})

In [153]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

#### 산술 연산 메서드에 채워 넣을 값 지정하기

In [154]:
df1 = pd.DataFrame(np.arange(12.).reshape(3, 4), columns=list('abcd'))

In [155]:
df2 = pd.DataFrame(np.arange(20.).reshape(4, 5), columns=list('abcde'))

In [156]:
df2.loc[1, 'b'] = np.nan

In [157]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [158]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [159]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [160]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [161]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [162]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [163]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### DataFrame과 Series 간의 연산

In [164]:
arr = np.arange(12.).reshape(3, 4)

In [165]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [166]:
arr[0]

array([0., 1., 2., 3.])

In [167]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [168]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [169]:
series = frame.iloc[0]

In [170]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [171]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [172]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [173]:
series2 = pd.Series(np.arange(3), index=['b', 'e', 'f'])

In [174]:
series2

b    0
e    1
f    2
dtype: int64

In [175]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [176]:
series3 = frame['d']

In [177]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [178]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [179]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 5.2.6 함수 적용과 매핑

In [180]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [181]:
frame

b         d         e
Utah   -0.326224 -0.081258 -0.254325
Ohio   -0.813620 -1.171720 -0.433315
Texas   0.466066  0.365837  0.789842
Oregon  1.073533  0.072033 -1.102987

In [182]:
np.abs(frame)

b         d         e
Utah    0.326224  0.081258  0.254325
Ohio    0.813620  1.171720  0.433315
Texas   0.466066  0.365837  0.789842
Oregon  1.073533  0.072033  1.102987

In [183]:
f = lambda x: x.max() - x.min()

In [184]:
frame.apply(f, axis=0)

b    1.887153
d    1.537557
e    1.892829
dtype: float64

In [185]:
frame.apply(f, axis=1)

Utah      0.244967
Ohio      0.738406
Texas     0.424005
Oregon    2.176520
dtype: float64

In [186]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [187]:
frame.apply(f)

b         d         e
min -0.813620 -1.171720 -1.102987
max  1.073533  0.365837  0.789842

In [188]:
format = lambda x: '%.2f' % x

In [189]:
frame.applymap(format)

b      d      e
Utah    -0.33  -0.08  -0.25
Ohio    -0.81  -1.17  -0.43
Texas    0.47   0.37   0.79
Oregon   1.07   0.07  -1.10

In [190]:
frame['e'].map(format)

Utah      -0.25
Ohio      -0.43
Texas      0.79
Oregon    -1.10
Name: e, dtype: object

### 5.2.7 정렬과 순위

In [199]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [200]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [201]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [202]:
frame = pd.DataFrame(np.arange(8).reshape(2, 4), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])

In [205]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [206]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [207]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [208]:
obj = pd.Series([4, 7, -3, 2])

In [209]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [210]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [211]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [212]:
frame = pd.DataFrame({'b':[4, 7, -3, 2], 'a':[0,1,0,1]})

In [213]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [214]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [215]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [216]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [218]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [219]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [220]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [221]:
frame = pd.DataFrame({'b' : [4.3, 7, -3, 2], 'a':[0, 1, 0, 1], 'c':[-2, 5, 8, -2.5]})

In [222]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [223]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### 5.2.8 중복 색인

In [224]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [225]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [226]:
obj.index.is_unique

False

In [227]:
obj['a']

a    0
a    1
dtype: int64

In [228]:
obj['c']

4

In [229]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [230]:
df

0         1         2
a -0.811483  0.090406 -2.051667
a -0.490160  0.805635 -0.223956
b  1.548660 -1.499685  0.954477
b -0.433592  0.166492  0.250924

In [231]:
df.loc['b']

0         1         2
b  1.548660 -1.499685  0.954477
b -0.433592  0.166492  0.250924

In [234]:
df = pd.DataFrame([
    [1.4, np.nan], 
    [7.1, -4.5],
    [np.nan, np.nan],
    [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two'])

In [235]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [236]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [237]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [239]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [240]:
df.idxmax()

one    b
two    d
dtype: object

In [241]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [242]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

### 5.3.1 상관관계와 공분산

In [245]:
import pandas_datareader.data as web

In [246]:
all_data = {ticker:web.get_data_yahoo(ticker) for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [247]:
price = pd.DataFrame({ticker:data['Adj Close'] for ticker, data in all_data.items()})

In [248]:
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

In [249]:
returns = price.pct_change()

In [250]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-01-12 -0.001396  0.004900 -0.011771 -0.011417
2021-01-13  0.016227 -0.017723  0.006560  0.004495
2021-01-14 -0.015127  0.016152 -0.015346 -0.008105
2021-01-15 -0.013731 -0.004497 -0.001737 -0.002293
2021-01-19  0.000551  0.005997  0.005314  0.007108

In [251]:
returns['MSFT'].corr(returns['IBM'])

0.5490144563572896

In [252]:
returns['MSFT'].cov(returns['IBM'])

0.00015534264777157332

In [254]:
returns.MSFT.corr(returns.IBM)

0.5490144563572896

In [255]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.463006  0.713868  0.655718
IBM   0.463006  1.000000  0.549014  0.513873
MSFT  0.713868  0.549014  1.000000  0.778389
GOOG  0.655718  0.513873  0.778389  1.000000

In [256]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000361  0.000143  0.000236  0.000206
IBM   0.000143  0.000263  0.000155  0.000138
MSFT  0.000236  0.000155  0.000304  0.000225
GOOG  0.000206  0.000138  0.000225  0.000275

In [257]:
returns.corrwith(returns.IBM)

AAPL    0.463006
IBM     1.000000
MSFT    0.549014
GOOG    0.513873
dtype: float64

In [258]:
returns.corrwith(volume)

AAPL   -0.078190
IBM    -0.063277
MSFT   -0.085768
GOOG   -0.156276
dtype: float64

In [259]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b' , 'b', 'c', 'c'])

In [260]:
uniques = obj.unique()

In [261]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [263]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [264]:
pd.value_counts(obj.values, sort=False)

d    1
b    2
c    3
a    3
dtype: int64

In [265]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [266]:
mask = obj.isin(['b', 'c'])

In [267]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [269]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [270]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [271]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [272]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [273]:
data = pd.DataFrame({'Qu1':[1,3,4,3,4], 'Qu2':[2,3,1,2,3], 'Qu3':[1,5,2,4,4]})

In [274]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [275]:
result = data.apply(pd.value_counts).fillna(0)

In [276]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0