In [3]:
import numpy as np

In [26]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [27]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 15.2 ms, sys: 1.31 ms, total: 16.5 ms
Wall time: 14.9 ms


In [28]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 572 ms, sys: 121 ms, total: 693 ms
Wall time: 695 ms


In [29]:
data = np.random.randn(2, 3)

In [31]:
data * 10

array([[ 11.29271465,  -4.3068247 , -12.29701615],
       [-17.62604211,  -2.33980064,  -1.65812928]])

In [32]:
data + data

array([[ 2.25854293, -0.86136494, -2.45940323],
       [-3.52520842, -0.46796013, -0.33162586]])

In [33]:
data.shape

(2, 3)

In [34]:
data.dtype

dtype('float64')

In [35]:
data1 = [6, 7.5, 8, 0, 1]

In [36]:
arr1 = np.array(data1)

In [37]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [38]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [39]:
arr2 = np.array(data2)

In [40]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
arr2.ndim

2

In [42]:
arr2.shape

(2, 4)

In [43]:
arr = np.arange(10)

In [44]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[5]

5

In [46]:
arr[5:8]

array([5, 6, 7])

In [47]:
arr[5:8] = 12

In [48]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [49]:
arr_slice = arr[5:8]

In [50]:
arr_slice

array([12, 12, 12])

In [51]:
arr_slice[1] = 12345

In [52]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [54]:
arr3d = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]])

In [55]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
old_values = arr3d[0].copy()

In [60]:
arr3d[0] = 42

In [61]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[0] = old_values

In [64]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [72]:
data = np.random.randn(7, 4)

In [73]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [74]:
data

array([[ 1.34562989, -0.34686414, -0.85286073, -0.71708375],
       [ 1.29175616,  0.12380808, -0.82644955, -0.92535517],
       [ 2.21460057,  1.28241419, -1.00714516,  0.58951982],
       [-1.04207288, -1.58658009, -0.90743646,  0.59636697],
       [ 0.91526832,  0.07850307,  0.92652676, -0.54692667],
       [-1.00389852,  0.36931218, -0.80391086,  1.37658338],
       [-2.13571613, -0.66203006, -1.17832276, -0.0778467 ]])

In [75]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [77]:
data[names == 'Bob']

array([[ 1.34562989, -0.34686414, -0.85286073, -0.71708375],
       [-1.04207288, -1.58658009, -0.90743646,  0.59636697]])

In [78]:
data[names == 'Bob', 2:]

array([[-0.85286073, -0.71708375],
       [-0.90743646,  0.59636697]])

In [79]:
data[~(names == 'Bob')]

array([[ 1.29175616,  0.12380808, -0.82644955, -0.92535517],
       [ 2.21460057,  1.28241419, -1.00714516,  0.58951982],
       [ 0.91526832,  0.07850307,  0.92652676, -0.54692667],
       [-1.00389852,  0.36931218, -0.80391086,  1.37658338],
       [-2.13571613, -0.66203006, -1.17832276, -0.0778467 ]])

In [81]:
arr = np.arange(15).reshape((3,5))

In [82]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [83]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [102]:
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
arr.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

## 4.2 유니버설 함수 : 배열의 각 원소를 빠르게 처리하는 함수

In [11]:
arr = np.arange(10)

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [16]:
x = np.random.randn(8)

In [17]:
y = np.random.randn(8)

In [19]:
np.maximum(x, y)

array([ 0.20807189, -0.15776145,  1.31031974,  0.77550007,  0.65842709,
        0.33843754, -0.85801884, -0.35424962])

In [20]:
arr = np.random.randn(7) * 5

In [24]:
arr

array([-0.70127503, -3.90221813, -1.9232569 , -3.96392229,  6.02697625,
       -6.04420908, 10.89092387])

In [25]:
remainder, whole_part = np.modf(arr)

In [26]:
remainder

(array([-0.70127503, -0.90221813, -0.9232569 , -0.96392229,  0.02697625,
        -0.04420908,  0.89092387]),
 array([-0., -3., -1., -3.,  6., -6., 10.]))

In [27]:
whole_part

array([-0., -3., -1., -3.,  6., -6., 10.])

In [28]:
arr

array([-0.70127503, -3.90221813, -1.9232569 , -3.96392229,  6.02697625,
       -6.04420908, 10.89092387])

In [29]:
np.sqrt(arr)

<ipython-input-29-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan,        nan,        nan, 2.45499007,
              nan, 3.30013998])

In [30]:
np.sqrt(arr, arr)

<ipython-input-30-164954cb2c14>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan,        nan,        nan,        nan, 2.45499007,
              nan, 3.30013998])

In [31]:
arr

array([       nan,        nan,        nan,        nan, 2.45499007,
              nan, 3.30013998])

In [32]:
x1 = np.arange(10)

In [33]:
x2 = np.arange(10)

In [34]:
x3 = np.add(x1, x2)

In [35]:
x3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
x4 = np.subtract(x1, x2)

In [37]:
x4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
x5 = np.power(x1, x2)

In [39]:
x5

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

## 4.3 배열을 이용한 배열지향 프로그래밍

In [57]:
points = np.arange(-2, 2, 1)

In [58]:
xs, ys = np.meshgrid(points, points)

In [59]:
ys

array([[-2, -2, -2, -2],
       [-1, -1, -1, -1],
       [ 0,  0,  0,  0],
       [ 1,  1,  1,  1]])

In [60]:
xs

array([[-2, -1,  0,  1],
       [-2, -1,  0,  1],
       [-2, -1,  0,  1],
       [-2, -1,  0,  1]])

### 4.3.1 배열 연산으로 조건절 표현하기

In [4]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [5]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [6]:
cond = np.array([True, False, True, True, False])

In [11]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

In [12]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [13]:
result = np.where(cond, xarr, yarr)

In [14]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [16]:
arr = np.random.randn(4, 4)

In [17]:
arr

array([[-1.18560118e+00,  1.53796910e+00, -7.63333420e-04,
        -1.61138474e-01],
       [ 1.12171909e+00,  6.97165872e-01, -1.46008964e+00,
        -3.39517384e-01],
       [ 2.84764059e-01, -5.96617221e-01,  4.81612239e-01,
         8.10122613e-01],
       [ 9.38016731e-01,  7.62887030e-01, -1.24446958e+00,
         9.58305563e-01]])

In [18]:
arr > 0

array([[False,  True, False, False],
       [ True,  True, False, False],
       [ True, False,  True,  True],
       [ True,  True, False,  True]])

In [20]:
np.where(arr > 0, 2, -2)

array([[-2,  2, -2, -2],
       [ 2,  2, -2, -2],
       [ 2, -2,  2,  2],
       [ 2,  2, -2,  2]])

In [21]:
np.where(arr > 0, 2, arr)

array([[-1.18560118e+00,  2.00000000e+00, -7.63333420e-04,
        -1.61138474e-01],
       [ 2.00000000e+00,  2.00000000e+00, -1.46008964e+00,
        -3.39517384e-01],
       [ 2.00000000e+00, -5.96617221e-01,  2.00000000e+00,
         2.00000000e+00],
       [ 2.00000000e+00,  2.00000000e+00, -1.24446958e+00,
         2.00000000e+00]])

### 4.3.2 수학 메서드와 통계 메서드

In [23]:
arr = np.random.randn(5, 4)

In [24]:
arr

array([[ 1.54366958,  1.33137959, -0.70036267,  0.47246146],
       [ 0.05350104, -0.90235376, -0.38273887, -0.98428127],
       [ 0.58861382, -0.39103184,  2.49791413, -0.29167768],
       [-0.24678517, -0.12411659, -0.67604277,  1.48321473],
       [ 1.62489683, -1.1313903 ,  1.19770163,  0.99542169]])

In [25]:
arr.mean()

0.29789967788128763

In [26]:
np.mean(arr)

0.29789967788128763

In [27]:
arr.sum()

5.957993557625753

In [28]:
arr.mean(axis=1)

array([ 0.66178699, -0.55396822,  0.60095461,  0.10906755,  0.67165746])

In [29]:
arr.sum(axis=1)

array([ 2.64714796, -2.21587286,  2.40381843,  0.4362702 ,  2.68662984])

In [30]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [31]:
arr.cumsum()

In [32]:
arr = np.array([[0,1,2], [3,4,5], [6,7,8]])

In [33]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [35]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

### 4.3.3 불리언 배열을 위한 메소드

In [37]:
arr = np.random.randn(100)

In [38]:
(arr > 0).sum()

45

In [39]:
bools = np.array([False, False, True, False])

In [41]:
bools.any()

True

In [42]:
bools.all()

False

### 4.3.4 정렬

In [43]:
arr = np.random.randn(6)

In [44]:
arr

array([ 0.48690512,  1.24370377, -0.17216168, -1.10355614, -0.33465442,
        0.6144314 ])

In [45]:
arr.sort()

In [46]:
arr

array([-1.10355614, -0.33465442, -0.17216168,  0.48690512,  0.6144314 ,
        1.24370377])

In [47]:
arr = np.random.randn(5, 3)

In [48]:
arr

array([[ 5.79737758e-01,  5.33872384e-01,  9.48102374e-01],
       [-3.94771013e-01, -1.45373915e+00, -1.00218349e+00],
       [ 5.03920181e-01, -5.28647088e-02, -7.58035001e-01],
       [-2.63614470e-04,  2.52522964e-01,  6.47795922e-01],
       [ 3.34607720e-01,  5.61518443e-01, -3.00385808e-01]])

In [51]:
arr.sort(1)

In [52]:
arr

array([[ 5.33872384e-01,  5.79737758e-01,  9.48102374e-01],
       [-1.45373915e+00, -1.00218349e+00, -3.94771013e-01],
       [-7.58035001e-01, -5.28647088e-02,  5.03920181e-01],
       [-2.63614470e-04,  2.52522964e-01,  6.47795922e-01],
       [-3.00385808e-01,  3.34607720e-01,  5.61518443e-01]])

In [53]:
large_arr = np.random.randn(1000)

In [54]:
large_arr.sort()

In [55]:
large_arr[int(0.05 * len(large_arr))]

-1.6200559668991434

### 4.3.5 집합 관련 함수

In [56]:
names = np.array(['Bob', 'Joe', 'Will','Bob', 'Will', 'Joe', 'Joe'])

In [57]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [58]:
ints = np.array([3,3,3,2,2,1,1,4,4])

In [60]:
np.unique(ints)

array([1, 2, 3, 4])

### 4.4 배열 데이터의 파일 입출력

In [61]:
arr = np.arange(10)

In [62]:
np.save('some_array', arr)

In [64]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.savez('array_archive.npz', a=arr, b=arr)

In [66]:
arch = np.load('array_archive.npz')

In [67]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

## 4.5 선형대수

In [70]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [72]:
y = np.array([[1, 2] ,[3, 4], [5, 6]])

In [73]:
np.dot(x,y)

array([[22, 28],
       [49, 64]])

In [74]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [76]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [77]:
from numpy.linalg import inv, qr

In [78]:
X = np.random.randn(5, 5)

In [80]:
mat = X.T.dot(X)

In [81]:
inv(mat)

array([[ 0.69919492,  0.54358842,  0.29242219, -0.0945269 , -0.19334948],
       [ 0.54358842,  2.03050979,  0.5580309 , -0.48761667, -0.88501565],
       [ 0.29242219,  0.5580309 ,  0.5067255 , -0.29992175, -0.15450413],
       [-0.0945269 , -0.48761667, -0.29992175,  0.42658151,  0.24819154],
       [-0.19334948, -0.88501565, -0.15450413,  0.24819154,  0.58437532]])

In [82]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -1.85375242e-16, -2.27099733e-17,
        -1.45466382e-17,  1.63197037e-17],
       [ 1.67278902e-16,  1.00000000e+00, -1.19596004e-16,
        -5.78277114e-17,  3.22260911e-16],
       [-1.28975997e-16, -9.29350290e-16,  1.00000000e+00,
         1.88829698e-16,  2.37846659e-16],
       [-5.30165787e-17,  1.33299817e-16,  1.01888137e-16,
         1.00000000e+00, -3.11708236e-17],
       [ 6.58067959e-17,  7.82219458e-16, -2.98261301e-17,
        -1.67624014e-16,  1.00000000e+00]])

### 4.7 계단 오르내리기 예제

In [83]:
nsteps = 1000

In [84]:
draws = np.random.randint(0, 2, size=nsteps)

In [85]:
steps = np.where(draws > 0, 1, -1)

In [86]:
walk = steps.cumsum()

In [87]:
walk.min()

-8

In [88]:
walk.max()

50