## 4.2 numpy 함수 다루기

### 가. numpy 배열 생성

In [1]:
import numpy as np

In [2]:
v1 = np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [3]:
v1 = np.arange(5)
print(v1)

[0 1 2 3 4]


In [4]:
v2 = np.arange(1,10,2, dtype=int)
v3 = np.arange(3.5, 10.5, 2, dtype=float)

In [5]:
print(v2)

[1 3 5 7 9]


In [6]:
print(v3)

[3.5 5.5 7.5 9.5]


In [7]:
v4 = np.arange(1,10,2)**2
v5 = np.arange(1,10,2)**3

In [8]:
print(v4)

[ 1  9 25 49 81]


In [9]:
print(v5)

[  1  27 125 343 729]


### 나. 행렬 만들기

In [10]:
v1 = np.arange(12)
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
v2 = v1.reshape(2, 6)
print(v2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [12]:
v3 = v1.reshape(2, 6, order="F")
print(v3)

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [13]:
v3 = np.arange(3.5, 10.5, 2, dtype=float)
print(v3)

[3.5 5.5 7.5 9.5]


In [16]:
v4 = np.arange(1,5).reshape(2,2)
print(v4)

[[1 2]
 [3 4]]


In [19]:
print(np.amax(v3))

9.5


In [18]:
print(np.amin(v4))

1


In [20]:
print(v3.dtype)

float64


In [21]:
print(v4.dtype)

int64
